### ISSUE TITLE
Document why "WPGraphiQL queries not matching Localhost GraphiQL"

### ISSUE THREAD

**Issue by emaildano** [gatsbyjs/gatsby-source-wordpress-experimental#101]
Is it normal for queries within the WordPress Dashboard using GraphiQL not to match the localhost version? When I run into errors I hop into WP for testing but the names don't match so it leaves me guessing.

`wpPost` vs. `post`

Thanks!

![Screen Shot 2020-07-29 at 10 51 19 PM](https://user-images.githubusercontent.com/1872327/88875019-75fa9700-d1ee-11ea-9c5d-0ebb029e5590.png)

![Screen Shot 2020-07-29 at 10 53 05 PM](https://user-images.githubusercontent.com/1872327/88875029-7e52d200-d1ee-11ea-844d-ff38fbadb36e.png)

**Comment by Kallirroi** [comment]
I would love to hear what others have to say but I thought it's because of schema merging: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/features/schema-merging.md

**Comment by TylerBarnes** [comment]
Ah, yeah this is indeed because of schema merging. Essentially what happens is that the source plugin automatically consumes the WPGraphQL schema and automatically creates a brand new schema from the data returned and from the original schema. While doing this it mixes the Gatsby node model schema with the WPGraphQL schema. This means we get proper caching and inc builds support as well as all the automatically generated filters that Gatsby provides but it also means that the node field names and types are slightly different. 
I'm going to keep this issue open as a reminder that docs around this need to be improved.

**Comment by TylerBarnes** [comment]
This is documented here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/features/graphql-wordpress-and-gatsby.md
