### ISSUE TITLE
Woocommerce: filters work on some products but not others

### ISSUE THREAD

**Issue by mattdabell** [gatsbyjs/gatsby-source-wordpress-experimental#103]
Hi,

I noticed that queries on products are quite hit-and-miss. Sometimes they work, other times no result is returned.

Not working despite the product clearly existing:

<img width="950" alt="Screenshot 2020-07-30 at 14 55 59" src="https://user-images.githubusercontent.com/12656149/88931859-46db3880-d275-11ea-8855-8c25d2d1bc69.png">

Working as expected if I select a different ID:

<img width="966" alt="Screenshot 2020-07-30 at 15 00 23" src="https://user-images.githubusercontent.com/12656149/88931985-696d5180-d275-11ea-9bf0-ba634ae26000.png">

Working fine in playground:

<img width="1122" alt="Screenshot 2020-07-30 at 15 03 43" src="https://user-images.githubusercontent.com/12656149/88932398-ebf61100-d275-11ea-908b-00caee919182.png">

Thanks!

**Comment by mattdabell** [comment]
This could potentially be something to do with the product type. It seems like variable products can be queried but simple products cannot.

**Comment by TylerBarnes** [comment]
Interesting, this definitely seems like a bug. Are you able to share a /graphql endpoint that has this issue so I can debug?

Thanks!

**Comment by mattdabell** [comment]
Hi @TylerBarnes, can use the same endpoint I've emailed you previously :)

**Comment by HumidBrains** [comment]
@TylerBarnes @mattdabell Any progress on this one? I suddenly experience a similar issue despite everything working well before. I think this happened when turning my variable products into simple ones. In fact, filters do not work at all on any of my simple products.

To spice things up, it turns out WP GraphiQL (WordPress) only list 10 out of the 27 (non filtered) products, whereas GraphiQL (Gatsby/Localhost) lists all 27 of them. However, if I then filter on a product slug (or any other argument), I do get the expected result from WP GraphiQL (WordPress), but an empty array from GraphiQL (Gatsby/Localhost).

**See screenshots below.**

**### WP GraphiQL (WordPress)**
<img width="1370" alt="WPGraphiQL_WordPress_Products" src="https://user-images.githubusercontent.com/5712389/93184277-51c22d80-f73c-11ea-9a14-b656803d92b4.png">
<img width="1358" alt="WPGraphiQL_WordPress_Filtered_Product" src="https://user-images.githubusercontent.com/5712389/93184310-5c7cc280-f73c-11ea-9e25-47eed15785e2.png">

### **GraphiQL (Gatsby/Localhost)**

<img width="1581" alt="GraphiQL_Gatsby_Localhost_AllProduct" src="https://user-images.githubusercontent.com/5712389/93184446-8c2bca80-f73c-11ea-96b1-d63d654415a2.png">
<img width="1580" alt="GraphiQL_Gatsby_Localhost_Filtered_Product" src="https://user-images.githubusercontent.com/5712389/93184491-99e15000-f73c-11ea-9657-fa719fbf618d.png">

**Comment by mattdabell** [comment]
I don't think there's any progress yet. I agree it definitely seems related to variable products, but something weird is going on for sure. I managed to work around the issue by up-front querying for every single product in gatsby-node then injecting the relevant products into the different taxonomy pages via context, basically using JS to filter instead of page queries & graphql. It works fine for now but I imagine breaks incremental builds & previews etc so hoping to refactor back to the normal way once things have stabilised.

**Comment by HumidBrains** [comment]
Thanks for the input @mattdabell. I've made another check now and filtering works for variable products, but not for simple products. I have not tried grouped or external products. If the bug is within WoographQl or gatsby-source-wordpress-experimental is hard for me to say. @TylerBarnes What's your take on this?

**Comment by TylerBarnes** [comment]
Thanks for the additional context @HumidBrains . The Woo schema is set up in a way this plugin isn't expecting so some additional logic needs to be added. Since we don't technically support Woo in this plugin just yet, I'm scoping this for after stable release. However, I am going to take a quick peek and see if this is a simple fix. If it is I'll cut a release soon. 
Thanks for your patience !

**Comment by TylerBarnes** [comment]
Hey Yall, I just had a look at this using @mattdabell 's API and I couldn't reproduce. I wonder if this was a Gatsby core bug that got fixed. What version of Gatsby are you on? @HumidBrains can you run `gatsby info` in your Gatsby directory?

@mattdabell I can access that product by id:
<img width="1048" alt="Screen Shot 2020-09-23 at 1 55 55 PM" src="https://user-images.githubusercontent.com/14190743/94068856-971dd500-fda4-11ea-8764-e2a73eb5c1b3.png">

@HumidBrains I'm able to filter by slug no problem as well.
![Uploading Screen Shot 2020-09-23 at 1.58.50 PM.png…]()

**Comment by TylerBarnes** [comment]
If it's not a Gatsby core bug that's been fixed, the other possibility is that the bug only happens after data is cached and updated via WP. But I haven't seen a bug like that since near the beginning of working on this plugin so it feels unlikely that that's it (not impossible though).

**Comment by smthomas** [comment]
Thank you for opening this issue. We recently moved this plugin over to the gatsbyjs monorepo and are trying to clean out this issue queue. This seems to be working after recent updates to the plugin. If you are still experiencing this issue, please provide a reproduction and open in the gatsbyjs repo.
