### ISSUE TITLE
Sourcing nodes fails when content contains protocol-relative image URLs (img src with double-slash)

### ISSUE THREAD

**Issue by benknight** [gatsbyjs/gatsby-source-wordpress-experimental#123]
I'm seeing the following error when sourcing my WordPress content:

```
 ERROR

 gatsby-source-wordpress  failed to process https://www.vietnamcoracle.com//pix6.agoda.net/hotelImages/636/6365854/6365854_19010317240071053512.jpg?s=480x360
MaxRedirectsError: Redirected 10 times. Aborting.
```

This is coming from a post that contains the following HTML:

```html
<img src="//pix6.agoda.net/hotelImages/636/6365854/6365854_19010317240071053512.jpg?s=480x360" />
```

A rudimentary search of the source code seems to imply the cause may be here: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/src/steps/source-nodes/create-nodes/process-node.js#L351

This check assumes that any img tag containing `src="/` must be a self-hosted asset. Obviously this doesn't account for protocol relative URLs.

**Comment by TylerBarnes** [comment]
Hi @benknight , sorry for the delayed response here - protocol relative url's are an anti-pattern https://www.paulirish.com/2010/the-protocol-relative-url/

Since the images still show up (just not as Gatsby images) we won't be implemented logic to handle this - I recommend instead using https:// url's everywhere. Since it's an anti-pattern and potentially insecure - it isn't worth adding the additional complexity to handle that case in this plugin. If you disagree please open a feature request on our new GatsbyJS portal https://portal.gatsbyjs.com/gatsby-cloud

Thank you!

**Comment by benknight** [comment]
Yes I understand however because WordPress is a CMS that generates HTML from WYSIWYG as well as third-party scripts (in the example I posted it's a widget provided by Agoda.com), its not always within developer's control. I suppose a plugin could do search/replace on protocol relative URLs. Anyway we've since migrated to Next.js so not concerned about this issue anymore. Thanks anyway for the followup.
