### ISSUE TITLE
Usage of URL is not clear

### ISSUE THREAD

**Issue by adamgen** [gatsbyjs/gatsby-source-wordpress-experimental#132]
This will not work:

```
{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: 'http://my-site.com',
      }
}
```

While this will:

```
{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: 'http://my-site.com/graphql',
      }
}
```

Took me a couple of hours of debugging the source under `node_modules` to figure it out. I suggest to automatically add an `http://` prefix and a `/graphql` suffix when they absent.

**Comment by TylerBarnes** [comment]
Thanks for this suggestion @adamgen . We aren't able to automatically add either of those for a couple reasons.
the `/graphql` endpoint can be reconfigured via a WordPress filter. This means if someone changes where the endpoint is, the plugin will never pick it up. For http, I'm not sure if we can programatically determine wether the endpoint is on http or https. I think in this case it might be better to change the `url` option to `graphqlUrl`, or provide a more helpful error message. Did you happen to check the docs? I'm curious because if you did, it needs to be clearer there as well.

**Comment by TylerBarnes** [comment]
This is fixed in https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/pull/284 which was published in `gatsby-source-wordpress-experimental@2.3.0`.

It will now try to append `/graphql` to the url when receiving HTML as a response. In the case that appending returns JSON, we display an error explaining how you should update your URL in settings. 

Thanks for opening this issue @adamgen !
