### ISSUE TITLE
htmlAst

### ISSUE THREAD

**Issue by ttstauss** [gatsbyjs/gatsby-source-wordpress-experimental#195]
Are there plans to add ast and htmlAst fields for content sourced from WordPress?

**Comment by TylerBarnes** [comment]
Hi @ttstauss , the goal of this plugin is to mirror the WPGraphQL schema as closely as possible. I love your idea but I believe any schema modifications like that should live in an external plugin rather than in the source plugin. We are planning on creating an official `gatsby-theme-wordpress` and this is the kind of modification that could live somewhere like that. Closing for now, but I'd love to see a plugin for this. Thanks for opening this issue!

**Comment by ttstauss** [comment]
@TylerBarnes, thanks for the explanation. I wasn't sure due to seeing ast/htmlAst in a lot of gatsby source plugins. Makes sense to me!
