### ISSUE TITLE
dont stop processing when image is not found

### ISSUE THREAD

**Issue by rburgst** [gatsbyjs/gatsby-source-wordpress-experimental#20]
currently if an image is not found, the processing stops. It would be nice to allow the process to carry on (maybe replace missing images with a bright red default image).

I already tried to patch `errorPanicker` but it still fails with

```
already re-queued http://dockerhost:8000/wp-content/uploads/2020/05/missing-image.jpg 5 times :( sorry.
Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
It's currently set to 5
```

**Comment by adriandmitroca** [comment]
Also, probably semi related - SVG files probably shouldn't raise warnings.

**Comment by TylerBarnes** [comment]
Hi @rburgst , thanks for opening an issue!

We aren't currently planning on allowing 404'ing images to continue the build because it's actually a feature that broken sites don't get deployed.
What we can do though is provide a link from the error to which page/post has the broken image so it can be removed. We have this set up currently for 404 images in html but it looks like that same logic isn't running for images in regular fields. I'll make sure this behaviour is consistent and provides a proper backend WP link to fix the problem in the admin area.

And @adriandmitroca agreed that SVG files shouldn't cause warnings.

**Comment by TylerBarnes** [comment]
Ah, it looks like I misread what you wrote. It already has an error message like what I mentioned, but you meant that you got your error message when trying to patch the source plugin.

So this is in "wont fix" territory, but what I can do that I think will be useful is to have it only throw warnings in development and errors in production.

**Comment by TylerBarnes** [comment]
Hmm, I just had a look at adding this in development but it adds significant complexity to an area of code which is already fairly complex. Since builds should always fail when the WP site content breaks, I think we shouldn't add this feature.
