### ISSUE TITLE
Question: hostingWPCOM config and ability to still use wordpress.com

### ISSUE THREAD

**Issue by dalecreativ** [gatsbyjs/gatsby-source-wordpress-experimental#205]
Just wanted to know if people on wordpress.com would still be able to move from `gatsby-source-wordpress` to `gatsby-source-wordpress-experimental`?    

Would it mean an end to wordpress.com hosted support once `gatsby-source-wordpress` is deprecated?

Thanks 👍

**Comment by TylerBarnes** [comment]
Hi @dalecreativ , unfortunately yes. There are too many critical issues with using the WP REST API in a decoupled setup which make creating a good integration an insurmountable problem. For that reason we decided to use WPGraphQL as a data source instead which requires installing WPGraphQL. In order to make this work smoothly we also needed to create our WPGatsby WP plugin.

If/when you're able to install the WPGraphQL and WPGatsby plugins on wordpress.com, we'll be able to support it, but until then we wont be able to. V3 of `gatsby-source-wordpress` will continue to exist but will not be actively maintained.

See https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/problems-with-v3.md for more info about why we made this decision.

Thanks for opening this issue and for using Gatsby 💜
