### ISSUE TITLE
403 error fetching nodes

### ISSUE THREAD

**Issue by Kallirroi** [gatsbyjs/gatsby-source-wordpress-experimental#21]
Hi, I have been running on the same issue all day and can't seem to progress much. None of the nodes queries are working (output below only mentions the Comment type, but I get errors for Pages, Users etc). 

```
 gatsby-source-wordpress  Request failed with status code 403

Error occured while fetching nodes of the "Comment" type.

GraphQL request to https://wordsinspace.net/shannon/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend

not finished source and transform nodes - 1.032s
not finished  gatsby-source-wordpress  fetching nodes - 1.009s
not finished  gatsby-source-wordpress  Category - 1.025s
not finished  gatsby-source-wordpress  Comment - 1.045s
not finished  gatsby-source-wordpress  ContentType - 1.088s
not finished  gatsby-source-wordpress  MenuItem - 1.142s
not finished  gatsby-source-wordpress  Menu - 1.194s
not finished  gatsby-source-wordpress  Page - 1.218s
not finished  gatsby-source-wordpress  Post - 1.225s
not finished  gatsby-source-wordpress  Tag - 1.228s
not finished  gatsby-source-wordpress  Taxonomy - 1.227s
not finished  gatsby-source-wordpress  TermNode - 1.249s
not finished  gatsby-source-wordpress  User - 1.245s
```

I am using `showQueryOnError: true` to inspect the query structure, here is the relevant output which results in `ERROR`: 

```
 gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  posts(first: $first, after: $after, where: { parent: null }) {
    nodes {
      author {
        id
      }
      categories(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      commentCount
      commentStatus
      comments(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      content
      contentType {
        node {
          id
        }
      }
      databaseId
      date
      desiredSlug
      editLast {
        id
      }
      enclosure
      excerpt
      featuredImage {
        id
        sourceUrl
      }
      guid
      id
      isRevision
      link
      modified
      modifiedGmt
      pingStatus
      pinged
      postFormats {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      slug
      status
      tags(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      template {
        __typename
        ... on DefaultTemplate {
          templateName
        }
        ... on SitemapTemplate {
          templateName
        }
      }
      termNames
      termSlugs
      terms {
        __typename
        ... on Category {
          id
        }
        ... on Tag {
          id
        }
      }
      title
      toPing
      uri
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

Some of you have mentioned that running this on a subdomain has been a problem (I am effectively trying to run it on a `http://domainname.com/user/` Wordpress instance as opposed to `http://wordpressname.com`), so I followed the advice in these issues without much success.

**Comment by TylerBarnes** [comment]
Hi @Kallirroi , thanks for opening an issue!
I'm trying to debug this but I'm having trouble narrowing down what's causing it. Do you have any server error logs from the 403 request? That might help debug. It's looking like this might be an axios bug but I'm not 100% sure yet. Still doing some digging.

**Comment by TylerBarnes** [comment]
It looks related to this https://github.com/axios/axios/issues/1535

I might just rip axios out and use fetch instead 🤷
In any case I'm on it!

**Comment by TylerBarnes** [comment]
Actually, looks like this is a problem with WordFence! 

I switched to using fetch and was able to get more info because it's returning an HTML page with the 403 and that html includes `A potentially unsafe operation has been detected in your request to this site</h1>\n\t<p>Your access to this service has been limited. (HTTP response code 403)` and then lower down `Wordfence is a security plugin installed on over 3 million WordPress sites. The owner of this site is using Wordfence to manage access to their site.</p>\n\t\t\t<p>You can also read the documentation to learn about Wordfence's blocking tools, or visit wordfence.com to learn more about Wordfence`

So you'll need to configure WordFence to stop blocking these requests. I'm not sure what's triggering it but I'll have to investigate how to provide a better error here

**Comment by TylerBarnes** [comment]
I'll be adding a clearer error message to the next release:

```

 gatsby-source-wordpress  Request failed with status code 403

The GraphQL request was forbidden.
If you are using a security plugin like WordFence or a server firewall you may need to whitelist your IP address or adjust your firewall settings for your GraphQL endpoint.
```

**Comment by Kallirroi** [comment]
Thanks so much for the help. I have played around with WordFence (found this https://github.com/gatsbyjs/gatsby/issues/6670#issuecomment-407945369 relevant comment) and ultimately disabled it, but to no success - I still get the stream of failed GraphQL queries. 

Current output with disabled Wordfence: 

```
> gatsby develop

success open and validate gatsby-configs - 0.038s
success load plugins - 1.059s
success onPreInit - 0.021s
success initialize cache - 0.014s
success copy gatsby files - 0.162s
success onPreBootstrap - 0.009s
⠀
info  gatsby-source-wordpress

	This is either your first build or the cache was cleared.
	Please wait while your WordPress data is synced to your Gatsby cache.

	Maybe now's a good time to get up and stretch? :D

success  gatsby-source-wordpress  ingest WPGraphQL schema - 1.763s
success createSchemaCustomization - 3.131s
success  gatsby-source-wordpress  Menu - 0.820s - fetched 1

 ERROR

 gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"http://wordsinspace.net/shannon/graphql","after":null}


 ERROR

 gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  terms(first: $first, after: $after, where: { parent: null }) {
    nodes {
      count
      databaseId
      description
      enqueuedScripts {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      enqueuedStylesheets {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      id
      link
      name
      slug
      termGroupId
      termTaxonomyId
      uri
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}



 ERROR

 gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"http://wordsinspace.net/shannon/graphql","after":null}


 ERROR

 gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  tags(first: $first, after: $after, where: { parent: null }) {
    nodes {
      count
      databaseId
      description
      enqueuedScripts {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      enqueuedStylesheets {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      id
      link
      name
      pages(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      posts(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      slug
      taxonomy {
        node {
          id
        }
      }
      termGroupId
      termTaxonomyId
      uri
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}


success  gatsby-source-wordpress  MenuItem - 1.424s
success  gatsby-source-wordpress  ContentType - 1.485s - fetched 3
success  gatsby-source-wordpress  Taxonomy - 1.492s - fetched 3

 ERROR

 gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"http://wordsinspace.net/shannon/graphql","after":null}


 ERROR

 gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  pages(first: $first, after: $after, where: { parent: null }) {
    nodes {
      author {
        id
      }
      categories(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      childPages(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      commentCount
      commentStatus
      comments(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      content
      contentType {
        node {
          id
        }
      }
      databaseId
      date
      desiredSlug
      editLast {
        id
      }
      enclosure
      enqueuedScripts {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      enqueuedStylesheets {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      featuredImage {
        id
        sourceUrl
      }
      guid
      id
      isFrontPage
      isRevision
      link
      menuOrder
      modified
      modifiedGmt
      wpParent: parent {
        __typename
        ... on Post {
          id
        }
        ... on Page {
          id
        }
        ... on MediaItem {
          id
        }
      }
      parentDatabaseId
      parentId
      slug
      status
      tags(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      template {
        __typename
        ... on DefaultTemplate {
          templateName
        }
        ... on SitemapTemplate {
          templateName
        }
      }
      termNames
      termSlugs
      terms {
        __typename
        ... on Category {
          id
        }
        ... on Tag {
          id
        }
      }
      title
      uri
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}



 ERROR

 gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"http://wordsinspace.net/shannon/graphql","after":null}


 ERROR

 gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  posts(first: $first, after: $after, where: { parent: null }) {
    nodes {
      author {
        id
      }
      categories(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      commentCount
      commentStatus
      comments(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      content
      contentType {
        node {
          id
        }
      }
      databaseId
      date
      desiredSlug
      editLast {
        id
      }
      enclosure
      enqueuedScripts {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      enqueuedStylesheets {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      excerpt
      featuredImage {
        id
        sourceUrl
      }
      guid
      id
      isRevision
      link
      modified
      modifiedGmt
      pingStatus
      pinged
      postFormats {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      slug
      status
      tags(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      template {
        __typename
        ... on DefaultTemplate {
          templateName
        }
        ... on SitemapTemplate {
          templateName
        }
      }
      termNames
      termSlugs
      terms {
        __typename
        ... on Category {
          id
        }
        ... on Tag {
          id
        }
      }
      title
      toPing
      uri
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}



 ERROR

 gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"http://wordsinspace.net/shannon/graphql","after":null}


 ERROR

 gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  users(first: $first, after: $after) {
    nodes {
      avatar {
        default
        extraAttr
        forceDefault
        foundAvatar
        height
        rating
        scheme
        size
        url
        width
      }
      capKey
      capabilities
      comments(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      databaseId
      description
      email
      enqueuedScripts {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      enqueuedStylesheets {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      extraCapabilities
      firstName
      id
      lastName
      locale
      mediaItems(first: 100) {
        nodes {
          id
          sourceUrl
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      name
      nicename
      nickname
      pages(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      posts(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      registeredDate
      slug
      uri
      url
      userId
      username
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}



 ERROR

 gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"http://wordsinspace.net/shannon/graphql","after":null}


 ERROR

 gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  categories(first: $first, after: $after, where: { parent: null }) {
    nodes {
      ancestors {
        id
      }
      wpChildren: children(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      count
      databaseId
      description
      enqueuedScripts {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      enqueuedStylesheets {
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      id
      link
      name
      pages(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      wpParent: parent {
        id
      }
      posts(first: 100) {
        nodes {
          id
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      slug
      taxonomy {
        node {
          id
        }
      }
      termGroupId
      termTaxonomyId
      uri
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}



 ERROR

 gatsby-source-wordpress  Unable to connect to WPGraphQL.

Error occured while fetching nodes of the "TermNode" type.

GraphQL request to http://wordsinspace.net/shannon/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend

not finished source and transform nodes - 2.236s
not finished  gatsby-source-wordpress  fetching nodes - 2.157s - 17 total
not finished  gatsby-source-wordpress  Category - 2.163s
not finished  gatsby-source-wordpress  Comment - 2.169s - fetched 10
not finished  gatsby-source-wordpress  Page - 2.164s
not finished  gatsby-source-wordpress  Post - 2.163s
not finished  gatsby-source-wordpress  Tag - 2.162s
not finished  gatsby-source-wordpress  TermNode - 2.150s
not finished  gatsby-source-wordpress  User - 2.142s
```

I will keep playing with other plugins and let you know if the culprit is something else. Thanks again for your help.

**Comment by jeremiahfallin** [comment]
@Kallirroi did you ever get this working?

**Comment by Kallirroi** [comment]
I started working on a clean Wordpress instance which solved it, but in hindsight it might have been a password protected Post that was the culprit. I didn't have to deal with this error message again ever since I started on a clean Wordpress instance.

**Comment by headit74** [comment]
I am getting the same error when I try to start the project.
`HeadITs-iMac:sergiot headit74$ yarn develop
yarn run v1.22.5
$ gatsby develop
success open and validate gatsby-configs - 0.055s
success load plugins - 0.694s
success onPreInit - 0.099s
success initialize cache - 0.013s
success copy gatsby files - 0.040s


warning [gatsby-source-wordpress]

This version of `gatsby-source-wordpress` will be deprecated soon.
The next major version (v4) is a complete rewrite in order to take advantage of WPGraphQL.
This allows us to support features like Preview and incremental builds and provides a much more stable experience.

Please upgrade to the BETA of `gatsby-source-wordpress@v4` by installing `gatsby-source-wordpress-experimental`.
These two packages are currently published under separate names to allow activating them side-by-side.
This makes migration between the two simpler.
Once the new plugin is stable it will be merged back in and published as `gatsby-source-wordpress` going forward.

Read this blog post for the beta announcement:
https://www.gatsbyjs.org/blog/2020-07-07-wordpress-source-beta/

Or get started with the new plugin here:
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/#readme

You can minimize this notice using the minimizeDeprecationNotice plugin option:

{
  resolve: "gatsby-source-wordpress",
  options: {
    minimizeDeprecationNotice: true
  },
},



success onPreBootstrap - 0.014s
⠀
info  gatsby-source-wordpress  

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

warning  gatsby-source-wordpress  Unable to find a single Node query for PaymentGateway
        This type will not be available in Gatsby.

success  gatsby-source-wordpress  ingest WPGraphQL schema - 7.128s
success createSchemaCustomization - 16.263s
The request failed with error code "ERR_TLS_CERT_ALTNAME_INVALID"
error "gatsby-source-wordpress" threw an error while running the sourceNodes lifecycle:

Cannot read property 'data' of undefined


  TypeError: Cannot read property 'data' of undefined
  
  - fetch.js:142 fetch
    [sergiot]/[gatsby-source-wordpress]/fetch.js:142:21
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - From previous event:
  
  - api-runner-node.js:554 Promise.catch.decorateEvent.pluginName
    [sergiot]/[gatsby]/src/utils/api-runner-node.js:554:9
  
  - From previous event:
  
  - api-runner-node.js:553 
    [sergiot]/[gatsby]/src/utils/api-runner-node.js:553:14
  
  - timers.js:439 processImmediate
    internal/timers.js:439:21
  
  - From previous event:
  
  - api-runner-node.js:526 
    [sergiot]/[gatsby]/src/utils/api-runner-node.js:526:13
  
  - From previous event:
  
  - api-runner-node.js:442 module.exports
    [sergiot]/[gatsby]/src/utils/api-runner-node.js:442:3
  
  - source-nodes.ts:97 _default
    [sergiot]/[gatsby]/src/utils/source-nodes.ts:97:9
  
  - source-nodes.ts:24 sourceNodes
    [sergiot]/[gatsby]/src/services/source-nodes.ts:24:9
  
  - interpreter.js:722 Interpreter.exec
    [sergiot]/[xstate]/lib/interpreter.js:722:27
  
  - interpreter.js:204 Interpreter.execute
    [sergiot]/[xstate]/lib/interpreter.js:204:22
  
  - interpreter.js:224 Interpreter.update
    [sergiot]/[xstate]/lib/interpreter.js:224:18
  
  - interpreter.js:125 
    [sergiot]/[xstate]/lib/interpreter.js:125:23
  
  - scheduler.js:60 Scheduler.process
    [sergiot]/[xstate]/lib/scheduler.js:60:13
  
  - scheduler.js:44 Scheduler.schedule
    [sergiot]/[xstate]/lib/scheduler.js:44:14
  
  - interpreter.js:121 Interpreter.send
    [sergiot]/[xstate]/lib/interpreter.js:121:29
  
  - interpreter.js:840 actor.id
    [sergiot]/[xstate]/lib/interpreter.js:840:23
  

success  gatsby-source-wordpress  Menu - 16.695s - fetched 2
success  gatsby-source-wordpress  ProductCategory - 18.718s - fetched 4
success  gatsby-source-wordpress  Customer - 19.674s - fetched 0
success  gatsby-source-wordpress  ContentType - 21.676s - fetched 4
success  gatsby-source-wordpress  MenuItem - 21.720s - fetched 13
success  gatsby-source-wordpress  VisibleProduct - 22.711s - fetched 9
success  gatsby-source-wordpress  ShippingClass - 22.737s - fetched 0
success  gatsby-source-wordpress  Coupon - 23.782s - fetched 0
success  gatsby-source-wordpress  ShippingMethod - 23.776s - fetched 4
success  gatsby-source-wordpress  PostFormat - 24.711s - fetched 5
success  gatsby-source-wordpress  Refund - 24.817s - fetched 0
error  gatsby-source-wordpress  (undefined) location: line 1, column: 645 
         Syntax Error: Expected Name, found Int "404"  

 Error path: undefined 

 If you haven't already, try adding define( 'GRAPHQL_DEBUG', true ); to your wp-config.php for more detailed error messages.
error  gatsby-source-wordpress  GraphQL vars: {"first":100,"url":"http://box2343.temp.domains/~sergiot7/graphql","after":null}
success  gatsby-source-wordpress  Order - 25.712s - fetched 0
success  gatsby-source-wordpress  Category - 25.720s - fetched 7
error  gatsby-source-wordpress  Error occured while fetching nodes of the "Page" type.
not finished source and transform nodes - 26.347s
not finished  gatsby-source-wordpress  fetching nodes - 25.742s - 48 total
not finished  gatsby-source-wordpress  Comment - 25.740s
not finished  gatsby-source-wordpress  Page - 25.737s
not finished  gatsby-source-wordpress  Post - 25.736s
not finished  gatsby-source-wordpress  ProductTag - 25.736s
not finished  gatsby-source-wordpress  ProductType - 25.736s
not finished  gatsby-source-wordpress  Product - 25.736s
not finished  gatsby-source-wordpress  Tag - 25.734s
not finished  gatsby-source-wordpress  TaxRate - 25.734s
not finished  gatsby-source-wordpress  Taxonomy - 25.734s
not finished  gatsby-source-wordpress  UserRole - 25.734s
not finished  gatsby-source-wordpress  User - 25.734s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
