### ISSUE TITLE
Add official starter with long lived backend API

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby-source-wordpress-experimental#212]
@jasonbahl has a WPGQL demo content site living somewhere we can use for data. 
As for the starter, we should fork a pre-existing well made starter and adapt it for WP. 
@LekoArts do you have any suggestions on starters or themes you've made that would be good to fork (or use without forking if there's a way to do that)? I always hear you make the very best of them!

**Comment by LekoArts** [comment]
Hehe, thank you!

I think https://github.com/LekoArts/gatsby-starter-minimal-blog would be a good fit. It's my most popular blog starter and can probably be filled with content with the default Wordpress models. It has `Pages` and `Posts` and those `Posts` also can have `Tags`.

It's built on https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog-core and https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog.

**Without forking option:**

You could do something similar to https://github.com/LekoArts/minimal-blog-yaml - so fill the generic GraphQL interfaces with content from WordPress. I started doing this as a test with a local WP instance but never found time to do it. It would be really cool to do it this way because then I could directly link it as an alternative source than MDX.

However, I also understand if we don't want an official starter example rely on my upstream changes in the theme 😆 

So with that in mind, you also have the option of **forking** it:

You could copy the contents of https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog into the existing starter and then essentially do the same https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog-core only with WordPress. Then you don't have any dependenies on those two themes and a "normal" starter (that doesn't rely on a theme).

**Comment by TylerBarnes** [comment]
Thanks @LekoArts ! Unfortunately the timeline for shipping this project has tightened by a lot :p So that means we'll be going with the most basic barebones starter I can find. Probably the official blog starter. Thanks for writing that all out though, and in the future we'll definitely reconsider when we have more time to spend on polishing things.

**Comment by TylerBarnes** [comment]
https://github.com/gatsbyjs/gatsby-starter-wordpress-blog
