### ISSUE TITLE
Input file contains unsupported image format

### ISSUE THREAD

**Issue by AndrewTraub** [gatsbyjs/gatsby-source-wordpress-experimental#253]
I'm getting this cryptic error with no idea which file is causing the issue:

success Build manifest and related icons - 0.003s
error "gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:

Input file contains unsupported image format

  Error: Input file contains unsupported image format

not finished Generating image thumbnails - 33.990s

I've deleted all svg, pdf, and mp4 files in the media library.

**Comment by acao** [comment]
It looks like you might be having an issue with `gatsby-plugin-manifest`, as it were, but it may be we don't need to transfer this issue to the gatsby monorepo anyways, since there might always be a resolution

This comment might be a diagnosis of and solution to your problem:

https://github.com/gatsbyjs/gatsby/issues/5638#issuecomment-393887551

let me know if that helps!

**Comment by TylerBarnes** [comment]
Hi @AndrewTraub , I'm closing this as it seems to not be related to this plugin but please let us know if you can't resolve your problem anyway and we can try to help more then.
