### ISSUE TITLE
WpMenu on Gatsby not returning any value while on GraphiQL returns

### ISSUE THREAD

**Issue by eduAbreu** [gatsbyjs/gatsby-source-wordpress-experimental#263]
Hello,

I'm trying to fetch the menus but on Gatsby GraphQL not getting any value while GraphiQL IDE on WordPress is working fine

GraphiQL
![image](https://user-images.githubusercontent.com/3449691/97895486-c02e6f80-1d2b-11eb-82e4-4512afbfe9fa.png)

Gatsby GraphQL
![image](https://user-images.githubusercontent.com/3449691/97895502-c58bba00-1d2b-11eb-929e-da7b26006071.png)

Anyone can help me with this?

**Comment by TylerBarnes** [comment]
Hi there, this is because menus with no location set are private data in WP. Using wp-graphiql isn't an effective debugging tool for Gatsby because it's authenticated by default and Gatsby makes only unauthenticated requests. See https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/using-data.md#menus for more info
