### ISSUE TITLE
Loss of data from WPGraphql endpoint

### ISSUE THREAD

**Issue by omegacoo** [gatsbyjs/gatsby-source-wordpress-experimental#289]
I am losing data from the WP side to the Gatsby side. I am getting most of the data, but nothing on authors, which WPGraphql is providing, confirmed WP side.

- gatsby-config.js:

```
{
  resolve: `gatsby-source-wordpress-experimental`,
    options: {
      url: `http://futurefoundry.onpressidium.com/graphql`,
  },
},
```

- GraphiQL query (WP side):

```
posts {
  edges {
    node {
      author {
        node {
          name
        }
      }
    }
  }
}
```

The above returns useful data.

- GraphiQL query (gatsby side):

```  
allWpPost {
  edges {
    node {
      author {
        node {
          name
        }
      }
    }
  }
}
```

Only returns `null`s

**Comment by omegacoo** [comment]
`"gatsby-source-wordpress-experimental": "2.4.0",`

**Comment by TylerBarnes** [comment]
Are you testing on the WP side using wp-graphiql? If so you should test with an external GraphiQL app. wp-graphiql makes authenticated requests so it's not an effective debugging tool for Gatsby (which makes only non-authenticated requests)

**Comment by TylerBarnes** [comment]
See https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#missing-data-in-gatsby for debugging steps 👍

**Comment by rickyPanzer** [comment]
I work with @omegacoo - do you have any suggestions for making authenticated requests for this plugin so that the author data for posts can be retrieved?

**Comment by rickyPanzer** [comment]
or rather, how to make an author public on a post, seems like this might need to be done on wp-graphql side. Any idea how to do that?

**Comment by TylerBarnes** [comment]
Hi @rickyPanzer , we've intentionally left out an authentication option, see https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/features/security.md for why that is (there's a good reason, I promise). 
You should make users public on the WPGraphQL side. In WordPress users are not public unless they have at least 1 published post. If your users have published posts and are still private, something is wrong in your WordPress site. If your users don't have published posts and you still want them to be public, you will need to filter them to be public in WPGraphQL. I'm not exactly sure how to do this. I would recommend checking the WPGraphQL docs first. If you can't find anything there I would recommend opening a new discussion on the WPGraphQL Github repo (https://github.com/wp-graphql/wp-graphql/discussions), or join the WPGraphQL slack and ask if anyone there knows how to achieve that (https://github.com/wp-graphql/wp-graphql#wpgraphql).

I'm closing this as the issue appears to be with WPGraphQL and/or site configuration rather than with this plugin but thanks @rickyPanzer and @omegacoo for opening an issue and for using this stack!

**Comment by omegacoo** [comment]
The issue ended up being the Advanced Access Manager plugin, with the option User Level Filter being turned off resolved it completely.

**Comment by TylerBarnes** [comment]
I'm so happy to hear you figured it out 😄  The WP plugin ecosystem is both amazing and horrific 😆
