### ISSUE TITLE
Get RawPrice return error

### ISSUE THREAD

**Issue by nguyenhuutinh** [gatsbyjs/gatsby-source-wordpress-experimental#291]
hi, how to get RAW price from woo?
I tried
.

```
.. on WpSimpleProduct {
          price(format: RAW)
 }
```
but I  got error when run compile.
`Unknown argument "format" on field "price" of type "WpSimpleProduct".
`

 it works on wpgraphql

thanks

**Comment by TylerBarnes** [comment]
Hi @nguyenhuutinh , field arguments aren't supported in this plugin and likely will never be supported due to the way this plugin works. Additionally Woo may work currently but isn't officially supported so you may run into problems with it. We plan to ensure Woo works well with this plugin in the future, but it's not part of our current work.
