### ISSUE TITLE
Error: Panicking because nodes appear to be being changed every time we run queries

### ISSUE THREAD

**Issue by luisduenas** [gatsbyjs/gatsby-source-wordpress-experimental#350]
Hi

I'm fetching data from a Graphql endpoint, it took like 5 hours to finish fetching all the data and now that I'm trying to query the data, I was able to fetch some of it, but as soon as I try to get the `featuredImage` field I'm getting this error

![image](https://user-images.githubusercontent.com/16164843/101540769-5a01c180-3955-11eb-9a5b-3339765a22f3.png)

And after running `gatsby develop` again, I can see all the available fields, but all the data is gone and any query returns empty data. To fix this, I need to clear the cache, build the site and wait another 5 hours.

This is the query that I'm using 
```
{
   allWpPost{
      nodes{
         featuredImage{
            node{
               altText
            }
         }
     }
   }
}
```

**Comment by TylerBarnes** [comment]
Hi @luisduenas , are you able to share a reproduction repo? It's hard to say what could be happening from the description.
Thanks!

**Comment by TylerBarnes** [comment]
It sounds like there's definitely a bug here (5 hours is not normal) but since we don't have access to a reproduction and no other reports we can't fix this. Please open a new issue on the GatsbyJS Github repo if this is still a problem and include a reproduction repo so we can debug/fix the issue.

Thank you :)
