### ISSUE TITLE
Normalizers are not executing

### ISSUE THREAD

**Issue by etnichols** [gatsbyjs/gatsby-source-wordpress-experimental#38]
No indication that normalizers are executing.

This is reproducible at https://github.com/etnichols/lead-to-read/tree/wp-experimental, observe that console.log statements in the normalizers aren't printed to console during the build process.

**Comment by etnichols** [comment]
Perhaps I filed this prematurely 😄 I see that https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md does not mention normalizers anywhere.

Are there plans to add support for normalizers in this plugin?

**Comment by TylerBarnes** [comment]
Hi @etnichols ! See this issue for an explanation https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/19

The `Type.beforeChangeNode` setting is what you're looking for. Out of curiosity what are you trying to normalize?
I'm wondering because maybe it's something this plugin should already be doing

Thanks!
