### ISSUE TITLE
Can't filter or sort child pages using wpChildren

### ISSUE THREAD

**Issue by jonlow** [gatsbyjs/gatsby-source-wordpress-experimental#411]
On pages (or hierarchal post types) you can't filter or sort wpChildren. This is essential for us as we need to be able to display page hierarchy. 

![image](https://user-images.githubusercontent.com/696226/104155088-88822900-543a-11eb-8fdd-6db64ddcfcf2.png)

However in the wordpress admin graphiql UI, we can filter/sort children 
![image](https://user-images.githubusercontent.com/696226/104155201-bebfa880-543a-11eb-85d3-a4834051fb49.png)

Is this easily fixed, or is there a working alternative to what I'm trying to achieve? Thanks!

**Comment by TylerBarnes** [comment]
This isn't currently possible. The best way to achieve this is to query top level nodes and filter there. So instead of querying `wpPage.wpChildren` you would query `allWpPage([filter by the parent id])`.

In the future, nested field filters will be possible but aren't currently. I'm closing this to consolidate with https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/60 since that chunk of work should be done at the same time
