### ISSUE TITLE
Document why we wont: Extend Auth options

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby-source-wordpress-experimental#54]
It would be great to have auth options to retrieve data on behalf of a specific user such as Admin, to see and have access to all possible information. In gatsby WordPress, I can use my user credentials for authorization, so it would be great to have it in this plugin too.

It will also solve this issue:
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/41

**Comment by TylerBarnes** [comment]
Hi @lnikell the reason I haven't added this is that it's a big security vulnerability for anyone using a Gatsby Preview instance (self-hosted or on Gatsby Cloud). The preview instance will run a build pulling all data including all private data and make that available on a public graphql endpoint. So all user data will be leaked. What's your use-case? 
Right now I'm inclined to keep it sourcing public data only. IMO any private data should be pulled in-browser. Maybe there's a use-case I'm missing though.

**Comment by TylerBarnes** [comment]
Hi @lnikell , thanks again for opening this issue. For now we're intentionally not adding auth to this plugin because it could mean all private data becomes public. Please feel free to re-open this issue or comment here if you have any additional thoughts or input. 

Thanks again!

**Comment by lnikell** [comment]
@TylerBarnes Thank you for the feedback. I don't know very well how Gatsby Preview works, but I will try to explain my use case, and maybe it will give some useful information. 

When I use WP as a data source, I don't need WP frontend at all and to prevent any security issues I completely disable access to that WP instance or by having basic auth or ip whitelisting, or in case of previous WordPress source plugin disable API access for anyone who does not have valid JWT token. 

In that case, I'm sure that only  specific user will have access to the data. So in my case, there are no public data available at all and if I make a call by authorized user I would like to have access to all information on WP.

I even think that it would be very great for Gatsby to have a "blank" WP theme and option for disabling API/graphql access to the WP instance for an unauthorized user from the WPGatsby plugin because for me it is not clear what should be the use case when you leave WP frontend available somehow too.

**Comment by TylerBarnes** [comment]
Thanks for elaborating! I can see why this is desireable, but I think using JWT for this is the wrong choice. 

Using JWT means all of your private data will be public via Gatsby when Gatsby authenticates and pulls all this data into it's own GraphQL server. Gatsby site data should be considered public data because that data can be statically rendered into a site which has no authentication or authorization considerations. This is even more true when running a preview server (either self-hosted or on Gatsby Cloud) because Gatsby's GraphQL server is available for public requests at `https://your-preview-url.com/__graphql` when running in this context.

In the end this will actually make WP data less secure than requiring no authentication. To protect your site in this way, the best bet is to use htaccess/htpassword or whitelisting IP's. The difference is that htpassword is authentication (you're allowed to make requests to the server) and JWT is authorization (you're allowed to pull private data from the server). These are both useful in their own ways but accomplish very different things in the context of sourcing large amounts of data from WP. 
Using JWT to lock down your api endpoint in this context means freely exposing all your private data publicly through Gatsby which is why this plugin option hasn't been added.

**Comment by TylerBarnes** [comment]
To add one more thing to this, the best way to pull private data is in-browser (using JWT) by allowing a specific user to authenticate/authorize as themselves. And JWT/Gatsby work great in that context. If you have specific fields which you want Gatsby to have access to you'll need to explicitly filter them in WP to be treated as public, for example if you want User nodes email fields to be public, you'll need to filter it to be.
