### ISSUE TITLE
Additional HTML Image Options

### ISSUE THREAD

**Issue by pjsachdev** [gatsbyjs/gatsby-source-wordpress-experimental#71]
It would be nice to have some additional configuration options for the images within the_content which are converted to Gatsby Img components. 

For instance, it would be particularly useful to optionally choose to use WebP images and to use traced SVG's instead of the blur up technique when lazy loading.

**Comment by TylerBarnes** [comment]
This is a great idea!

**Comment by erick-go** [comment]
It would be awesome if this would be implemented. In my example, the rest of my images are WebP and use tracedSVG, so besides performance, it would also mean more consistency...

**Comment by erick-go** [comment]
@TylerBarnes Is there any indication when this feature will be released?

**Comment by TylerBarnes** [comment]
Hi @erick-go , currently I'm the only maintainer and I'm a bit swamped - we're hiring a few more engineers on our team which will help the situation. Because of this it's hard to say in the near term when we'll get to this feature but you can expect our velocity to increase soon :+1: 

If you're interested or know anyone who's looking for a job, you can [apply here](https://gatsbyjs.com/careers/staff-software-engineer--integrations-4331862003). Thanks! :)

**Comment by erick-go** [comment]
That's good to hear.. (the increasing team members part). I wish I'd fit that job description. Someday... gl

**Comment by smthomas** [comment]
Thank you for opening this issue. We recently moved this plugin over to the gatsbyjs monorepo and are trying to clean out this issue queue. We documented this feature to look at for a future roadmap item and are going to close this issue out. If you want to add additional visibility to this feature, you can request it at https://portal.gatsbyjs.com/

**Comment by erick-go** [comment]
I've opened a request at: https://portal.gatsbyjs.com/gatsby-cloud/p/wordpress-additional-image-options-webp-for-inline-images-inside-thecontent
