### ISSUE TITLE
Missing localFile images after upgrading to 1.0.10

### ISSUE THREAD

**Issue by woodwoerk** [gatsbyjs/gatsby-source-wordpress-experimental#82]
Hey, this is a possible regression since 1.0.7, after reverting back to 1.0.7 everything works as expected.

I have a static query that fetches a bunch of images from an ACF gallery, and since upgrading to 1.0.10 it's not returning all available images

```
const { wp } = useStaticQuery(graphql`
    query Footer {
      wp {
        global: footerSettings {
          footerSettings {
            imageBank {
              localFile {
                ...FooterImage
              }
            }
          }
        }
...
```

- In WordPress GraphiQL: imageBank contains 30 images (as expected)
- In Gatsby GraphiQL, on first start with a clean cache: imageBank contains 16 images
- In Gatsby GraphiQL, on subsequent starts without a clean cache: imageBank only contains a single image

Private reproduction (@TylerBarnes has access): https://github.com/woodwoerk/nuori-fi-2020

The relevant query is at:  https://github.com/woodwoerk/nuori-fi-2020/blob/master/src/hooks/useFooterSettings.js

Cheers!

**Comment by TylerBarnes** [comment]
Hey @woodwoerk , thanks for catching this!

The reason is that I had fixed a bug where many more images than were actually referenced were being fetched. Turns out that overfetching was covering up this other bug where images only referenced in non-node root fields (like options) weren't being properly recognized and fetched. Upgrade to `gatsby-source-wordpress-experimental@1.0.12` for a fix :)

**Comment by woodwoerk** [comment]
Fab! Thanks so much for the speedy response
